apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-config
  namespace: airbnb
data:
  # 속성과 비슷한 키; 각 키는 간단한 값으로 매핑됨
  max_reservation_per_person: "10"
  ui_properties_file_name: "user-interface.properties"
